### ISSUE TITLE
Hide Anyline text below rectangle area

### ISSUE THREAD

**Issue by achinverma** [Anyline/anyline-ocr-examples-android#1]
Hi, I wan to hide the Anyline text below rectangle area which is used to scan the number ,please guide me?

![device-2016-11-26-145216](https://cloud.githubusercontent.com/assets/2811593/20639385/13a061de-b3e8-11e6-9890-f3adb6c819e8.png)

**Comment by steffyP** [comment]
Hi, 
I think you are talking about the watermark, right? As you are using a free "Community License key", the watermark will always be visible. If you decide to use Anyline for your commercial project, you need to buy a "Commercial License Key" which may have no watermark included.
