### ISSUE TITLE
Application is crashing when Initializing the Anyline SDK

### ISSUE THREAD

**Issue by ishwarverma39** [Anyline/anyline-ocr-examples-android#13]
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.toyota.oneapp.stage-oVe3F1Cxhu6HgdKOyiF41Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.toyota.oneapp.stage-oVe3F1Cxhu6HgdKOyiF41Q==/lib/x86, /data/app/com.toyota.oneapp.stage-oVe3F1Cxhu6HgdKOyiF41Q==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libopencv_java3_al.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at io.anyline.AnylineSDK.<clinit>(SourceFile:1)
        at io.anyline.AnylineSDK.init(SourceFile:1)`

**Comment by patrickAnyline** [comment]
Hello,

are you by chance trying to run the app on an x86 device? Because we currently don't support the x86 architecture.

Best regards,
Patrick

**Comment by ishwarverma39** [comment]
Thanks, for the response.
Yes, I am using  Pixel XI (x86) emulator, so which cpu type I have to choose.

**Comment by patrickAnyline** [comment]
Hey @ishwarverma39,

currently you would have to use an ARM image for the emulator or use a real device to deploy on.
Depending on which Android version you are trying to run it on, you might not actually find an image for emulation, though it should be included in Android 9 & 11: https://developer.android.com/studio/releases/emulator#support_for_arm_binaries_on_android_9_and_11_system_images

Best regards,
Patrick

**Comment by ishwarverma39** [comment]
Please let us know when x86 support is available we will update the Anyline SDK version. 

As of now I am closing this issue then.
