### ISSUE TITLE
crashing at (SourceFile:100)

### ISSUE THREAD

**Issue by pesmobile** [Anyline/anyline-ocr-examples-android#2]
D/CameraController1: Skip camera opening: A camera is already open.

and the exception log is

java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference
                                                                                 at at.nineyards.anyline.camera.CutoutView.setRect(SourceFile:100)

**Comment by mcerman** [comment]
Hi @pesmobile,

could you please describe a little bit more in detail under what circumstances this crash happens?

Do you install the APK directly on your phone, or do you create a new Android Studio project from the example source code and upload the build on your phone? Do you do any modifications to the code? On what phone does the crash happen? What scan mode causes this crash? Are you using stock Android?
