### ISSUE TITLE
Set Language Method missing in SDK 35

### ISSUE THREAD

**Issue by poonam13041987** [Anyline/anyline-ocr-examples-android#26]
We was using "setLanguages()" in SDK version 22 in previously. But in SDK version 35 this method is not there so please suggest hoe we can add language in  SDK 35 
Example:
anylineOcrConfig.setLanguages("tessdata/eng_no_dict.traineddata");

**Comment by rricarrdo** [comment]
Hi!

All parameters for loading Tesseract languages (.traineddata files) have been removed with Anyline v26. Please have a look at the [release notes](https://documentation.anyline.com/toc/platforms/android/release_guide/release_notes_archive.html#anyline-sdk-26) for Anyline v26 for more information.

Besides that, the standard Universal Serial Number scan mode was greatly improved, so you might not need to use a custom model anymore. Please try to use the default ["Universal Serial Number Scan Mode"](https://documentation.anyline.com/toc/demos/index.html).

On a side note, Anyline v37+ uses a new version of the License Key so, to use the newest versions, please require a new license key with our commercial team.

Best regards,
Ricardo

**Comment by poonam13041987** [comment]
While scanning any number or text "addScanResultListener" not calling.
