### ISSUE TITLE
ScanResultListener not getting called

### ISSUE THREAD

**Issue by poonam13041987** [Anyline/anyline-ocr-examples-android#27]
While scanning any number or text "addScanResultListener" not calling. my integration code are below

   // see ScanScrabbleActivity for a more detailed description
    AnylineOcrConfig anylineOcrConfig = new AnylineOcrConfig();
    // use predefined whitelist and regular expression
    anylineOcrConfig.setCharWhitelist(AnylineOcrConfig.AnylineOcrRegex.ISBN.getWhiteList());
    anylineOcrConfig.setValidationRegex(AnylineOcrConfig.AnylineOcrRegex.ISBN.getRegex());
    // AUTO ScanMode automatically detects the correct text without any further parameters to be set
    anylineOcrConfig.setScanMode(AnylineOcrConfig.ScanMode.AUTO);

    //init the scanViewPlugin config
    ScanViewPluginConfig ocrScanViewPluginConfig = new ScanViewPluginConfig(getApplicationContext(), "isbn_view_config.json");
    //init the scan view
    OcrScanViewPlugin scanViewPlugin = new OcrScanViewPlugin(getApplicationContext(), anylineOcrConfig, ocrScanViewPluginConfig, "OCR");
    //init the base config used for camera and flash
    BaseScanViewConfig ocrBaseScanViewConfig = new BaseScanViewConfig(getApplicationContext(), "isbn_view_config.json");
    //set the scan Base config
    scanView.setScanViewConfig(ocrBaseScanViewConfig);
    //set the scan view plugin to the scan view
    scanView.setScanViewPlugin(scanViewPlugin);
    //add the scan result listener
    scanViewPlugin.addScanResultListener(new ScanResultListener<OcrScanResult>() {
        @Override
        public void onResult(OcrScanResult result) {
            Toast.makeText(getApplicationContext(), result.toString(), Toast.LENGTH_SHORT).show();
            /*if (!result.toString().isEmpty()) {
                Toast.makeText(getApplicationContext(), result.toString(), Toast.LENGTH_SHORT).show();
            }*/
        }

    });
    scanView.getCameraView().enableBarcodeDetection(new NativeBarcodeResultListener() {
        public void onFailure(String e) {
            Log.e("Error while scanning", e);
        }
        public void onSuccess(List<Barcode> barcodes) {
            if (barcodes != null && !barcodes.isEmpty()) {
                setScanData(barcodes.get(0).getRawValue());
            }
        }
    }, null);

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
