### ISSUE TITLE
Creating Custom document ocr

### ISSUE THREAD

**Issue by darkdoctor** [Anyline/anyline-ocr-examples-android#3]
Hello.

Found this SDK and want to buy it.

First, I compiled the demo one and Id like to ask if we can create a custom scan like the MRZ. 

We have some kind of documents and we want to use ocr on them. 

Can we use ocr like (x : 0 , y: 20 ) so we can get values from some points ( like mrz )

**Comment by brad007** [comment]
Hi, any example on how to scan something like an identity document?

**Comment by ale-anyline** [comment]
Hi Brad,
You can find an example of the MRZ scanner implementation in our documentation: https://documentation.anyline.com/toc/demos/index.html#mrz-demo
