### ISSUE TITLE
Question regarding Meter Reading

### ISSUE THREAD

**Issue by AnuragNegiAndroid** [Anyline/anyline-ocr-examples-android#31]
Hi Team,
I know the question I am going to ask is somewhat silly. But I still, need confirmation. In the Anyline library for android, I was just checking the Meter read functionality. Is there any way to ensure that the reading is taken only from the real physical meter, not from any photo or any sort of paper with some digits?

"Help Needed"

**Comment by danielalbertini** [comment]
Hi,

thank you for the interest in Anyline. We do have that capabilities build and we have a huge customer using it widely already in production. But this is currently not yet available in our public SDK.

Please get in touch Herwig Hollauf via mail ( herwig at anyline.com ). He is one of our Customer Success Managers and will gladly help you out.

Best regards,
Daniel

**Comment by AnuragNegiAndroid** [comment]
Thanks, @danielalbertini for the quick response. Will surely contact CSM. 
Best regards,
Anurag
