### ISSUE TITLE
Proguard issue for Android

### ISSUE THREAD

**Issue by rokibhasan06** [Anyline/anyline-ocr-examples-android#39]
I needed to add following lines to _proguard-rules.pro_ to support minifyEnabled build

`-keepclassmembers class at.nineyards.anyline.** {*;}`

Following is the setup for my release build variant.

```
release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
```

You should add the proguard rule in your ReadMe section

**Comment by ricardocolombo** [comment]
Hi! 

The proguard information is included in our Android Documentation, but we will make sure to bring it also into the Cross-Platform's documentation. 

Thank you for your feedback!
