### ISSUE TITLE
eror in adnroid

### ISSUE THREAD

**Issue by canraar07** [Anyline/anyline-ocr-examples-android#44]
i'm get eror in android 
    
  `  java.lang.RuntimeException: Script not set or does not exist in the required path. 
    Are you auto generating the anyline_assets.json in your build.gradle? Or use the AssetUtil to copy the required stuff out of the apk manually?
    Core Exception: CmdFile does not exist or cannot be accessed.`
    
    how to fix it?
    Anyline version 42.0.0

**Comment by berndkamplanyline** [comment]
We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
