### ISSUE TITLE
Can we create a custom scan view to do OCR on a identity document to capture image and text.

### ISSUE THREAD

**Issue by harishmedamoni** [Anyline/anyline-ocr-examples-android#5]
Hi Team,

we have a requirment to scan a identity document and do OCR to read text on document and should be able to get image of the document.

Can you please help us to provide the sample code.

Thanks,
Harish

**Comment by harishmedamoni** [comment]
Hi,

Can you please provide me an update on this.

Thanks,
Harish

**Comment by lore-any** [comment]
Dear @harishmedamoni,

Here you can find out our documentation: [https://documentation.anyline.com/toc/products/id/index.html]
Please let us know if you need further guidance.
