### ISSUE TITLE
Upgrade information: Accessing Cutout Rect

### ISSUE THREAD

**Issue by adarzulfu** [Anyline/anyline-ocr-examples-android#50]
Hello,
I try to upgrade the version from 11 to 43.0.0.

Is there any way to get cutout rect or cutout position bounds? 

**Version 11**
we could access them `scanView.getCutoutRect().bottom` on `onCameraOpened` of `CameraOpenListener`

**Version 43**
I tried to access `ScanViewPlugin.getCutoutRect()` on `UIChangeListener` methods but all of them returns null. 

Thank you

**Comment by berndkamplanyline** [comment]
Can you please check if this issue still exists in the latest version? We recently made some changes to the cutout rect.

If it still persists, please read below:


We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
