### ISSUE TITLE
Duplicate class a.a found in modules

### ISSUE THREAD

**Issue by Muran-Hu** [Anyline/anyline-ocr-examples-android#51]
Hi,

I use several libs which are obfuscated. As a result, I get the following build error:

`Duplicate class a.a found in modules jetified-anylinesdk-43.1.0-runtime (io.anyline:anylinesdk:43.1.0) and jetified-xxx-3.0.0-preview-runtime (another library)
`

because another lib also has obfuscated a.a class.

![image](https://user-images.githubusercontent.com/10492550/223312588-b8be8762-3059-4c38-bc76-e844e286461c.png)

Could you please use a flattened package hierarchy in your ProGuard rules to move obfuscated classes in some unique packages to prevent conflicts mentioned above with other libraries?

Thanks in advance!

**Comment by berndkamplanyline** [comment]
Hi, could you please raise a support request using our Helpdesk.

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
