### ISSUE TITLE
VIN Scan Placeholder and Text Recognition animation not displaying

### ISSUE THREAD

**Issue by bala-suresh** [Anyline/anyline-ocr-examples-android#6]
Hi,

i am calling ScanVehicleIdentificationNumberActivity.java to scan a VIN number.
Scanner loading fine and reading number fine. But sometimes scan placeholder and text recognition effect not displaying when i started from a fragment (even activity sometimes). passing vin_view_config.json, but no luck. Could anyone pls suggest on this. thank you. 
![InkedScreenshot_2019-07-24-14-51-23-219_com manheim mobilede_LI](https://user-images.githubusercontent.com/19900976/61782016-f68bf800-ae22-11e9-90d0-16f103149315.jpg)

**Comment by lore-any** [comment]
Dear @bala-suresh, this issue should not occur within the latest Anyline Android SDK version 26.1.
