### ISSUE TITLE
Overlay-cutout does not working

### ISSUE THREAD

**Issue by AngelinaFedorova** [Anyline/anyline-ocr-examples-android#7]
Hello. We just updated the library to version 21 and discovered that the overlay for cutout does not working anymore. In json config, changing these parameters (outerColor and outerAlpha) does not change anything.
"viewPlugin": {
         "cutoutConfig": {
            ...
             },
             "outerColor": "000000",
             "outerAlpha": 0.8,
             ...
         }
I was checked sample [project](https://github.com/Anyline/anyline-ocr-examples-android/tree/master/AnylineSDK-Examples/AnylineSDK-Examples-Source)
and the same issue presented there as well.
Also was try set this value programmatically and this does not take affect.
`val scanViewPluginConfig = ScanViewPluginConfig(context, VIN_SCANNER_CONFIG)`
`scanViewPluginConfig.cutoutConfig.outerColor = ContextCompat.getColor(context, R.color.red)`
Android versions on which there was a check: Android 7.1.2; Android 10.0
On version 19, everything worked as expected and these parameters applied from config.
Is there way for change "outerColor" and "outerAlpha" for "cutoutConfig" in 21 version of the library?

**Comment by lore-any** [comment]
Dear @AngelinaFedorova,

Here is Lorena from Anyline. Thank you for the heads up! 
We will investigate the issue and come back to you as soon as possible with an update.

Best,
Lorena

**Comment by lore-any** [comment]
Dear @AngelinaFedorova,

I am happy to come back to you with an answer to the above issue. There was indeed a bug withing our SDK. The fix will be available in our next release. 

Thank you for your patience.

Best,
Lorena K.

**Comment by lore-any** [comment]
Dear @AngelinaFedorova. As we did not receive any answer from you on this issue, we consider it closed. If you still encounter the issue or if there are any other issues, please feel free to open a new one and we will come back to you ASAP.
