### ISSUE TITLE
Empty licence key

### ISSUE THREAD

**Issue by arefhosseini** [Anyline/anyline-ocr-examples-android#70]
Hi,

I was running the example app and it crashed because of the below error. 
```
io.anyline2.core.LicenseException: 
++++++++++ Anyline License Exception ++++++++++
The license key is empty.                                                                                                    +++++++++++++++++++++++++++++++++++++++++++++++
```
How can I fix it? 

Thanks.

**Comment by berndkamplanyline** [comment]
@arefhosseini Please follow the directions here on how to obtain a trial license: https://documentation.anyline.com/main-component/license-key-generation.html
