### ISSUE TITLE
lopencv Crash in new Android Studio Iguana

### ISSUE THREAD

**Issue by Aashir1111** [Anyline/anyline-ocr-examples-android#75]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3_al.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
at java.lang.System.loadLibrary(System.java:1661)
at io.anyline2.AnylineSdk.<clinit>(SourceFile:1)

I'm facing this crash after update Android studio version and Sdk Version 
Please help me to resolve it.

**Comment by berndkamplanyline** [comment]
Hi, could you please raise a support request using our Helpdesk.

We don't actively monitor the Github Issues, please raise a support request using the Anyline Helpdesk. Link to Anyline Helpdesk: https://support.anyline.com/

When raising a support request based on this Github Issue, please fill out and include the following information:

---
Support request concerning Anyline Github Repository: [URL to relevant Anyline Github Repository here]
Support request based on Github Issue: [URL to relevant Github Issue here]

---

Thank you so much!
